version: '3.8'

services:
  client:
    image: bmigeri/grpc-client:1.0
    build: ./client
    command: go run *.go
  server:
    image: bmigeri/grpcserver:1.0
    build: ./server
    ports:
      - 8080:8080
    command: go run *.go -b 0.0.0.0
